* week 1: introduction to the command line
** what is the command line?
- a way of talking to the computer.
  - GUIs vs commands
- the bash language
  
** why would you used the command line
- on your computer, everything is a file
- "plain text" - what is this?
  - demo with docx and plain text file.
- what are some rich text file formats?
  - what are some plain text file formats?
- why use command line?
  - we can manipulate plain text quite easily

** navigation
- on your computer, everything is in a folder
- "directory structure" folder system on your computer
  - tree: root and branches
  - "directory"

#+begin_src
pwd

cd

cd ..

cd ~

ls

# flags
ls -l -a
#+end_src

Home vs root folder

*** Practice: Spend a few minutes navigating up and down the directory structure

** creating files and folders / reading
Navigate to the place where you want to keep your files for this class.

#+begin_src 
touch 

mkdir 664

rmdir 664
#+end_src

** group activity: searching text 10/10
In partners, figure out how to use the GREP command. What does it do?
Advanced: how do you use it to search across multiple nested folders?
(hint: its a flag!)

#+begin_src 
grep queer notecards.org
#+end_src

** redirect

#+begin_src 
grep queer notecards.org >> queer_words.txt
#+end_src

*** Group Challenge 15 / 15
Practice using grep on your own machine, searching for a word in
different files. Then, use redirect to save the results to a separate
file. 

** time to do challenge!
Spend some time navigating NYC Open Data website for a dataset you
like. 

Download the [[https://data.cityofnewyork.us/Social-Services/NYC-Women-s-Resource-Network-Database/pqg4-dm6b/about_data][NYC Women's Resource Network Database]] from [[https://opendata.cityofnewyork.us/][NYC Open Data]].
Search the text for words like "women" or "migrant" or something else.
Then, using redirect, save the results to a separate file. (hint:
you'll need to use grep and redirect).

#+begin_src
grep TERM ~/Downloads/..csv >> migrant.txt
#+end_src

** time to download and install Anaconda (highly recommended) or Python
