* introduction to the command line
by filipa calado

** what is the command line?
- a way of talking to the computer.
  - GUIs vs commands
- the bash language
  
** why would you used the command line
- "plain text" - what is this?
  - demo with docx and plain text file.
- what are some rich text file formats?
  - what are some plain text file formats?
- we can manipulate plain text quite easily

** navigation
- folder system on your computer
  - tree: root and branches
  - "directory"

#+begin_src
whoami

pwd

cd

cd ..

cd ~

ls

ls -l -a
#+end_src

Spend a few minutes navigating up and down the directory structure. 

** creating files and folders / reading
#+begin_src 
touch 

mkdir info-664

wc 

wc -lha
#+end_src

** group activity: searching text 10/10
In partners, figure out how to use the GREP command. What does it do?
Advanced: how do you use it to search across multiple nested folders?
(hint: its a flag!)

10/10

** pipes
takes the output of one command and makes it the input of another.

#+begin_src 
grep queer notecards.org | wc
#+end_src

can add flags to wc, like -l for line count. 

** (if time) redirect

#+begin_src 
grep queer notecards.org >> queer_words.txt
#+end_src

*** Group Challenge
Practice using grep on your own machine, searching for a word in
different files. Then, use redirect to save the results to a separate
file. 

** time to do challenge!
Download the [[https://data.cityofnewyork.us/Social-Services/NYC-Women-s-Resource-Network-Database/pqg4-dm6b/about_data][NYC Women's Resource Network Database]] from [[https://opendata.cityofnewyork.us/][NYC Open Data]].
Search the text for words like "women" or "migrant" or something else.
Then, using redirect, save the results to a separate file. (hint:
you'll need to use grep and redirect).

#+begin_src
  grep migrant
~/Downloads/NYC_Women_s_Resource_Network_Database_20240828.csv >>
~/Desktop/migrant.txt
#+end_src

** time to download and install Anaconda (highly recommended)
